### ISSUE TITLE
walking backwards

### ISSUE THREAD

**Issue by bigpoppa66** [FuryFight3r/ScrappingSimulator#106] opened 2023-03-28 14:23 UTC
### Describe the bug

the character is permanantly walking backwards i cannot stop it when i move forward and 
let go just starts walking back again.
and the keys are  in the wrong order  awsd do not control it it is the directional keys

**Comment by FuryFight3r** [comment] 2023-03-28 21:38
Hi there @bigpoppa66, sorry this is happening for you, in most cases any issue linking to involuntary character movement generally is caused by either a Controller or Steering Wheel being active on your system and sending false signals to the Character.

This has been fixed in the v0.32.1 Update, though unfortunately I am running into a few issues with this update and as of yet have no ETA for the release of this patch.

Otherwise for the time being you could try unplugging external Controller devices, such as Game Pads, Steering Wheel, Hand Brake etc which should stop these devices sending false signals to the game 🙂👍

**Comment by bigpoppa66** [comment] 2023-03-29 15:45
thank you for that it was my steering wheel i have unplugged it and its fine 
thank you very much for your help

**Closed** 2023-03-30 18:11 UTC
Labels: BUG, Resolved
