### ISSUE TITLE
[Bug]: Stamina

### ISSUE THREAD

**Issue by GizmosGaming** [FuryFight3r/ScrappingSimulator#107] opened 2023-04-13 23:50 UTC
### Describe the bug

My character never gets tired, so I can never use the bed. It happen before the last patch and I still happens with the latest patch.

### Screenshot(s)/Video(s)

![Scrap error sleep](https://user-images.githubusercontent.com/112440633/231905811-458fc7f7-5904-406d-89cc-95a01c6c3082.png)

### Console output

Saved Version was a Game Version using a Different Time Scale - Now Converting Saved Energy to the New Time Scale

### Player Logs

[Scrapping Simulator.zip](https://github.com/FuryFight3r/ScrappingSimulator/files/11227497/Scrapping.Simulator.zip)

**Comment by GizmosGaming** [comment] 2023-04-14 00:26
So I tried to start a new game and it happen again when I went to sleep. Now time stands still as well.

[Scrapping Simulator.zip](https://github.com/FuryFight3r/ScrappingSimulator/files/11227581/Scrapping.Simulator.zip)
![Scrap error sleep 2](https://user-images.githubusercontent.com/112440633/231910866-ca75db21-d50b-415f-892e-4cb0091dc58c.png)

**Comment by FuryFight3r** [comment] 2023-04-14 00:57
Hi there @GizmosGaming thank you for reporting this, as a temporary fix you can press [F1] to open the command panel and then type the 'fix_time' command followed by the 'fix_energy' command which should kickstart time and reconnect the energy to the corresponding time, nevertheless I hope to have a hotfix out asap 🙂👍

**Comment by FuryFight3r** [comment] 2023-04-14 05:21
Hi again @GizmosGaming 

Thanks again for reporting this, I have added a small update to the v0.32.2 Hotfix including a fix for this and a few other issues 🙂👍

**Closed** 2023-04-14 05:22 UTC
Labels: BUG, Resolved

**Comment by GizmosGaming** [comment] 2023-04-14 22:06
![Scrap error sleep 3](https://user-images.githubusercontent.com/112440633/232162762-10afc501-48df-4eed-8ba0-c67bc3489557.png)

after the patch. Do I need to start a new game?

**Comment by FuryFight3r** [comment] 2023-04-14 22:25
> ![Scrap error sleep 3](https://user-images.githubusercontent.com/112440633/232162762-10afc501-48df-4eed-8ba0-c67bc3489557.png)
> 
> after the patch. Do I need to start a new game?

Hi there @GizmosGaming 
You shouldn't need to start a new game, though it does look like your energy doesn't match the Time of day, you may just need to do the fix_time & fix_energy commands which fingers crossed should fix the issue 🙂👍

**Comment by GizmosGaming** [comment] 2023-04-15 01:36
I did what you said and it worked. I played through the day and saved my game. 
Exited the game and reloaded. Same errors as before. Time is going as normal now. But my energy is not going down.

**Comment by FuryFight3r** [comment] 2023-04-15 01:46
That is very strange, as the energy should go down when time advances as they both run off the same system, I will look into this and see what the issue is 🙂👍
