### ISSUE TITLE
character walking on its own

### ISSUE THREAD

**Issue by sdcole06** [FuryFight3r/ScrappingSimulator#98] opened 2023-03-07 14:09 UTC
### Describe the bug

I just bought this game and the character is stuck walking backwards I have unplugged my keyboard and it still does it so its not on my end when I walk forward he will walk forward but as soon as I let off he walks backwards very annoying

### Reproduction Steps

just play the game

### Expected behaviour

the character walks backwards on his own

**Comment by FuryFight3r** [comment] 2023-03-07 22:44
Hi there @sdcole06  and thank you for reporting this.
I am currently stuck on another report with a similar problem, is it possible you have a Controller active and connected on your system? As this can cause issues for the Character.

While the character is moving on its own is there any errors related the the Player/Character when pressing F5?

This is certainly a difficult one to solve as it's like trying to find a word in the world's dictionary, without knowing what the word or even what letter it begins with.

If at all possible, could you provide your Player Logs (found at: https://github.com/FuryFight3r/ScrappingSimulator/wiki/Where-to-find-Scrapping-Simulator-Save-File-and-Error-Logs) which I may be able to look through and check for any errors.

**Comment by sdcole06** [comment] 2023-03-07 23:52
I am having trouble finding the file I double checked my controller is unhooked, I saved and restarted, it still does it when I hit F5. so pretty much when I walk forward if I let go it automatically walks backwards it does that all the time it will stop for a minute or so when I save and go back in but then it continues

**Comment by FuryFight3r** [comment] 2023-03-08 00:01
Pressing F5 won't fix the issue, it just brings up a Debug Menu that will show you any errors that may have arisen. Otherwise you can follow the wiki guide link I had sent earlier to find the Player.log files, which if you could send to me gives me all the Debug Log Print outs and some basic Info on your System Specs which hopefully can help narrow down what the cause of this issue is 👍

**Comment by sdcole06** [comment] 2023-03-08 00:20
[Player-prev.log](https://github.com/FuryFight3r/ScrappingSimulator/files/10915162/Player-prev.log)
[Player.log](https://github.com/FuryFight3r/ScrappingSimulator/files/10915164/Player.log)

**Comment by sdcole06** [comment] 2023-03-08 00:21
I hope this helps LOVING THE GAME!!

**Comment by sdcole06** [comment] 2023-03-08 00:32
The referenced script (AutoMoveAndRotate) on this Behaviour is missing!
The referenced script on this Behaviour (Game Object 'Question_Mark') is missing!
Renderer 'PCB' is registered with more than one LODGroup ('PCB' and 'PCB').
Joystick disconnected ("Controller (Xbox One For Windows)").
The tree SM_Env_Tree_06 must use the Nature/Soft Occlusion shader. Otherwise billboarding/lighting will not work correctly.
The tree SM_Env_Tree_01 must use the Nature/Soft Occlusion shader. Otherwise billboarding/lighting will not work correctly.
The tree SM_Plant_Grass_03 must use the Nature/Soft Occlusion shader. Otherwise billboarding/lighting will not work correctly.
The tree SM_Tree_02 must use the Nature/Soft Occlusion shader. Otherwise billboarding/lighting will not work correctly.
The tree SM_Tree_03 must use the Nature/Soft Occlusion shader. Otherwise billboarding/lighting will not work correctly.
Warning: found the Weather Selection was equal to 0 this could be an indicator that weather will become stuck in a loop! Let's double Check

my F5 errors

**Comment by sdcole06** [comment] 2023-03-08 00:32
i didnt think about my wheel ill try it

**Comment by sdcole06** [comment] 2023-03-08 00:36
THAT WORKED THANK YOU!

**Comment by FuryFight3r** [comment] 2023-03-08 00:40
> THAT WORKED THANK YOU!

Great to hear, I will see about disabling any form of Input other than Keyboard and Mouse through Unity, if I am still un able to do so I will see about putting a warning on Game Start-up recommending to Unplug any Controller like Input Device for best game experience. :)

**Closed by FuryFight3r** 2023-03-08 00:40 UTC
Labels: BUG, Pending More Info
