### ISSUE TITLE
[Bug]: DISASSEMBLING PROBLEM

### ISSUE THREAD

**Issue by senoks** [FuryFight3r/ScrappingSimulator#109] opened 2023-04-26 19:25 UTC
### Describe the bug

Can not disassemble any electrical appliances after crafting silver/gold bars. You can put the appliances on the workbench, but are now unable to do anything with this. The only thing you can do is move/rotate or go to the Pawn Shop and sell your stuff.

### Expected behaviour

Put the electrical on the workbench, the only thing you can do is move and rotate. 
This worked fine until I made Silver/Gold bar.

**Comment by FuryFight3r** [comment] 2023-04-26 22:52
That is very odd, I will do some testing and see if I can replicate the issue and find out what is going wrong, though that is very strange the Chem Set is breaking the Disassembly table as they are in no way connected, either way I will look into t and have a patch asap 🙂

**Comment by senoks** [comment] 2023-04-27 15:12
Perhaps the update can be a reason for this problem, even the saved game got this problem.
I had to start a new game from start, and i don't know if this helped, since i must play everything from start.


________________________________
Fra: FuryFight3r ***@***.***>
Sendt: torsdag 27. april 2023 00:52
Til: FuryFight3r/ScrappingSimulator ***@***.***>
Kopi: Stig Blackie Enoksen ***@***.***>; Author ***@***.***>
Emne: Re: [FuryFight3r/ScrappingSimulator] [Bug]: DISASSEMBLING PROBLEM (Issue #109)


That is very odd, I will do some testing and see if I can replicate the issue and find out what is going wrong, though that is very strange the Chem Set is breaking the Disassembly table as they are in no way connected, either way I will look into t and have a patch asap 🙂

**Comment by senoks** [comment] 2023-04-27 16:38
Hi, after starting a brand new game, after the latest update looks like it work, but there are an another bug.
That is, if you place ingot in to the shelf, save and reload the game, the ingots are missing.
I got gold bars in the carrybox and the gold doesn't disappear, only the bars in the shelf are missing after loading the save.

________________________________
Fra: FuryFight3r ***@***.***>
Sendt: torsdag 27. april 2023 00:52
Til: FuryFight3r/ScrappingSimulator ***@***.***>
Kopi: Stig Blackie Enoksen ***@***.***>; Author ***@***.***>
Emne: Re: [FuryFight3r/ScrappingSimulator] [Bug]: DISASSEMBLING PROBLEM (Issue #109)


That is very odd, I will do some testing and see if I can replicate the issue and find out what is going wrong, though that is very strange the Chem Set is breaking the Disassembly table as they are in no way connected, either way I will look into t and have a patch asap 🙂

**Comment by FuryFight3r** [comment] 2023-04-27 21:40
Thank you for that, I will hopefully have a patch out asap fixing these issues 🙂👍

**Comment by FuryFight3r** [comment] 2023-04-27 23:11
> Hi, after starting a brand new game, after the latest update looks like it work, but there are an another bug. That is, if you place ingot in to the shelf, save and reload the game, the ingots are missing. I got gold bars in the carrybox and the gold doesn't disappear, only the bars in the shelf are missing after loading the save.

Hi there @senoks, would it be possible if you could provide your safe file for me to test and diagnose the issue? I have just come to the realisation that a lot of these random bugs are occurring due to an Error that may appear when loading in, that says:

"ERROR: Unable to Parse/Convert: *VERSION* to a number format - The Saved Game version did not appear to have the word Alpha nor a Comma - Aborting attempt to convert version, Version will be set to 28.6 by default to run any required fix code"

Which happens when the game cannot convert the text value: 32.4 to a number value: 32.4 - which if the game Fails to convert this value it resorts back to an old version (28.6) so when loading your game data every bug fix that arose through the stages of updates will be applied to your save file, which in turn forces the Save/Load system to load the Old Ingot Shelf System and not the New one.

Though I have found that in most cases this Error has arisen from the System Language changing the games vales from '32.4' to '32,4' which seems to break the Version Checker system, there is at least 5 checks the game goes through to try and convert this number correctly though sometimes it just fails to convert it when it contains a comma. If you too are facing this same error each time you are loading your game, then this will likely be the cause of these random issues, if you are able to provide any save file that is producing this error I will be able to use it to try create a patch :)

**Comment by FuryFight3r** [comment] 2023-06-24 23:13
Thank you again for reporting this Issue, this should hopefully now be resolved with the new Saving/loading of Objects in the form of an ID :)

**Closed by FuryFight3r** 2023-06-24 23:13 UTC
Labels: BUG, Pending More Info
