### ISSUE TITLE
Stop Time Travel

### ISSUE THREAD

**Issue by SpercWolf** [FuryFight3r/ScrappingSimulator#157] opened 2024-04-01 23:45 UTC
### What is your Suggestion?

Slow down the passage of time. It goes by way to fast.

### How will this suggestion fit into the Scope of Scrapping Simulator?

It will give more time throughout the day to scrap metals

### How would the Game and Community benefit from this suggestion?

The game wouldn't feel so hyper speed

**Comment by FuryFight3r** [comment] 2024-04-02 06:40
Hi there @SpercWolf and thank you for your suggestion 🙂

Unfortunately I don't have much to go off with this, as another user has reported their days are only lasting around 5 minutes, where days are coded to last around 36 minutes per 24 Game Hrs (26-30 Minutes of playable day time minus Sleep time). 

Unfortunately on my system, both in Unity and the Built Version of the Game, days are lasting the expected 36 minutes, so as far as myself and the code goes it's all working as expected. 

The other player who reported this issue hasn't yet been able to provide any supporting evidence (Log files, Save File, Photo/Video) of this bug and has gone radio silent since I asked, so I haven't been able to track down or patch this bug seeing as the time of day is working perfectly on my end and any changes directly to day length would cause adverse effects to those whose time is currently working properly.

For your suggestion are you meaning that 36 Minutes is considered hyper speed? Or are you too experiencing this 5 Minute Day bug?

If the latter, then I may need some more information to try find the root cause of this bug such as Logs 🙂👍

**Comment by FuryFight3r** [comment] 2024-04-09 17:46
Hello again @SpercWolf 

Seeing as you have not responded or provided any further information in regards to this, I will be closing the issue.

Feel free to explain further the issue you are facing and Re-Open the issue at your convenience 👍

**Closed by FuryFight3r** 2024-04-09 17:46 UTC
Labels: Suggestion, Pending More Info

**Comment by FuryFight3r** [comment] 2024-04-16 09:18
Hi again @SpercWolf 
This may or may not be fixed in the [[v0.37.1 Update]](https://store.steampowered.com/news/app/1496640/view/6758289089647243234) - Which still yields a 30 minute day for me personally, as I wasn't able to replicate the fast day bug, but instead of trying to calculate a day length on startup, I've just set that end calculated value as the direct correlation of a day length, which in turn should stop different outcomes for players, as potentially the calculations were not correct for some players, but I have no way of knowing without logs in this instance, but hopefully its all good now anyway 👍
