### ISSUE TITLE
[Bug]: Crucible

### ISSUE THREAD

**Issue by CrazyJamie1** [FuryFight3r/ScrappingSimulator#36] opened 2022-06-27 01:55 UTC
### Describe the bug

The Crucible looks interesting and when using it to make ingots it glitches the cooling timer of the ingot moulds.

### Reproduction Steps

1. Have a square crucible
2. Melt metal in it
3. Put it in the mould when ready
4. Enjoy

### Expected behaviour

The usual of being able to make ingots

### Screenshot(s)/Video(s)

![Bug CI](https://user-images.githubusercontent.com/108179614/175845827-aa19cdd2-b1ec-40ce-8377-dd1c4be3a97e.JPG)
![Bug CI2](https://user-images.githubusercontent.com/108179614/175845835-09c39de5-5516-494e-aafa-fc33f1b6c708.JPG)
![Bug CI3](https://user-images.githubusercontent.com/108179614/175845842-cf1a58f7-9ef0-4938-8025-275b9d7bade7.JPG)

### Console output

Forgot to grab it again

### Player Logs

[Player.log](https://github.com/FuryFight3r/ScrappingSimulator/files/8988099/Player.log)
[Player-prev.log](https://github.com/FuryFight3r/ScrappingSimulator/files/8988100/Player-prev.log)

**Comment by CrazyJamie1** [comment] 2022-06-27 02:00
and reloading doesn't fix the issue

**Comment by CrazyJamie1** [comment] 2022-06-27 02:19
![Bug CI4](https://user-images.githubusercontent.com/108179614/175847856-6fff8c5c-1245-42f0-b586-9cf155d43f43.JPG)
This is what happens when you try to use the return crucible button in the bug fixes section

**Comment by FuryFight3r** [comment] 2022-06-27 02:42
Hi there CrazyJamie,
I am currently working on a fix for this, though it is proving quite difficult, could you possibly send in your Save file so I can look into why this may be happening?
Aus2004 was also facing the same issue, which it seems no matter how many times I replace the broken crucible it always gets replaced with another broken one, but when attempting this in a handful of other testing saves I have or even a brand new save, the crucible is fine, so this one really has me stumped, hopefully with your save file it may help in finding what the cause of this bug is

**Comment by CrazyJamie1** [comment] 2022-06-28 02:50
I sent it through discord

**Comment by FuryFight3r** [comment] 2022-07-01 06:03
Hi there CrazyJamie,
Thanks again for reporting this issue, it has now been fixed in the v0.30.2 Hot Fix :)

**Closed by FuryFight3r** 2022-07-01 06:03 UTC
Labels: BUG, WIP
